config/routes.rb
Rails.application.routes.draw do

  root to: redirect('/gossips')

  get '/welcome/:first_name', to: 'static#welcome'

  get '/contact', to: 'static#contact'

  get '/team', to: 'static#team'

  get '/form', to: 'static#form'

  get '/show_new_gossip/:id', to:'gossips#show_new_gossip'

  resources :cities, only: [:show]

  resources :users, only: [:index, :show]

  resources :gossips do
    resources :comments, except: [:show, :index, :new]
  end
  
  resources :sessions, only:[:new,:create,:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  validates :name, presence: true
  validates :zip_code, presence: true, uniqueness: true
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_many :comment_likes
  belongs_to :user
  belongs_to :gossip
  belongs_to :parent_comment, class_name: 'Comment', optional: true
  has_many :child_comments, class_name: 'Comment', foreign_key: :parent_comment_id, dependent: :destroy
end

app/models/comment_like.rb
class CommentLike < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title, length: {in: 3..14}
  validates :content, presence: true
  belongs_to :user
  has_many :gossip_likes
  has_many :comments
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
end

app/models/gossip_like.rb
class GossipLike < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :description, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
  validates :age, presence: true
  validates :city_id, presence: true


  belongs_to :city
  has_many :comment_likes
  has_many :gossip_likes
  has_many :comments
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def show
    @city = City.find(params[:id])
    puts "showcities"*10
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  
  def create
    @comment = Comment.create!(content: params[:content],gossip_id: params[:gossip_id] ,user_id: User.all.sample.id)
    flash[:notice] = 'Le commentaire a bien été publié !'
    redirect_to request.referrer
  end

  def edit
    @comment = Comment.find(params['id'])
  end

  def update
    @comment = Comment.find(params['id'])
    @path = Gossip.find_by(id: @comment.gossip_id)
    if @comment.update(content: params['comment']['content'])
      flash[:notice] = 'Le commentaire a bien été mis à jour !'
      redirect_to "/gossips"
    else
      flash[:alert] = @comment.errors.full_messages[0]
      render 'edit'
    end
  end

  def destroy
    @gossip = Gossip.find(params[:gossip_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:notice] = 'Le commentaire a bien été supprimé !'
    redirect_to "/gossips"
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def index
    @gossips = Gossip.order(:id)
  end

  def new_gossip
    @gossip = Gossip.new()
    puts "#{'$'*60} #{@gossip}"
  end

  def show_new_gossip
    @gossips = Gossip.all
    @gossip = Gossip.find(params[:id])
    @user = @gossip.user
    @city = @user.city
    puts "#{'M'*60} #{@gossip}"
  end 


  def create
    @gossip = Gossip.new(title: params['title'], content: params['content'], user_id: User.all.sample.id)
    puts "#{'€'*60} #{@gossip}"
    if @gossip.save
      flash[:notice] = 'Le potin a bien été créé'
      redirect_to "/show_new_gossip/#{@gossip.id}"
    else
      flash[:alert] = @gossip.errors.full_messages[0]
      render 'gossips/index'
    end 
  end

  def edit
    @gossip = Gossip.find(params[:id])
    puts "editgossip"*10
  end

  def update
    @gossip = Gossip.find(params[:id])
    post_params = params.require(:gossip).permit(:title, :content)
    if @gossip.update(post_params)
      flash[:notice] = 'Le potin a bien été mis à jour'
    redirect_to '/gossips'
    else
      flash[:alert] = @gossip.errors.full_messages[0]
      render 'gossips/index'
    end
  end
  
  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    flash[:notice] = 'Le potin a bien été détruit !'
    redirect_to '/gossips'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
    end
  
    def create
      # cherche s'il existe un utilisateur en base avec l’e-mail
      user = User.find_by(email: params[:email])
    
      # on vérifie si l'utilisateur existe bien ET si on arrive à l'authentifier (méthode bcrypt) avec le mot de passe 
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        # redirige où tu veux, avec un flash ou pas
        flash[:notice] = "Well play,#{@user.first_name}"
        redirect_to '/'
    
      else
        flash.now[:danger] = 'Invalid email/password combination'
        render 'new'
      end
    end
  
    def destroy
        session.delete(:user_id)
    end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def welcome
    @first_name = params[:first_name]
  end

  def form
    puts "$" * 80
    puts "Fomulaire nouveau potin "
    puts "$" * 80
  end

  def contact
    puts "$" * 80
    puts "Page : Nous contacter"
    puts "$" * 80
  end

  def team
    puts "$" * 80
    puts "Page : Team"
    puts "$" * 80
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    puts "index"*10
  end

  def show
    @user = User.find(params[:id])
    puts "show"*10
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        User.find_by(id: session[:user_id])
    end

    def log_in(user)
        session[:user_id] = user.id
    end
    
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/show.html.erb
<div>
<p> Ville : <%= @city.name %></p>

<% @city.users.each do |user| %>
<% user.gossips.each.with_index do |gossip, index| %>
<h3> Gossip n°<%= gossip.id + 1 %> - <%= gossip.title %></h3>
<%= gossip.user.first_name %> <%= gossip.user.last_name %>
 <% end %>
 <% end %>

app/views/comments/edit.html.erb
<h1>Bienvenue dans la page pour éditer le commentaire n°<%= params['id'] %> du potin n°<%= params['gossip_id'] %> </h1>

  <center>
    <%= form_for @comment, url:gossip_comment_url do |f| %>

      <div class="form-group">
        <label>Commentaire</label>
        <%= f.text_field :content, class: 'form-control' %>
      </div>

      <div class="form_group" data-turbo=false>
        <button type="submit" class="btn btn-success" method: :patch> Modifier le commentaire</button> 
  
      </div>
      <div>
      </div>
    <% end %>


  <%= button_to "Supprimer le commentaire", gossip_comment_path, class:"btn btn-danger", form: { data: { turbo_confirm: "Veux-tu supprimer ce commentaire ?" } }, style:"display: inline;", method: :delete %>

  </center>

app/views/gossips/edit.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Teams</title>

    <style>
    .bg-light {
    background-color: #bd915a!important;
    }

    </style>
    
</head>
   
   <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Gossip Project</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="http://localhost:3000/">Accueil<span class="sr-only"></span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/team">Notre équipe</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/contact">Nous contacter</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>


<h1> Editer un potin </h1>

<%= form_for @gossip do |form|%>

<div class="form-group">
<label>Titre du potin</label>
<%= form.text_field :title, class: 'form-control'%>
</div>

<div class="form-group">
<label>Contenu du potin</label>
<%= form.text_area :content, class: 'form-control'%>
</div>

<div class="form-group">
<button type="submit">Modifier le potin</button>
</div>

<% end %>

app/views/gossips/index.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Accueil</title>

    <style>
      body {
        /* background-color: #bd915a; */
        background-image: url("/assets/anneaux.jpg");
        background-size: cover; /* Redimensionner l'image pour couvrir tout le contenu */
        background-position: center; /* Centrer l'image horizontalement et verticalement */
      }

      main {
        margin: 5rem;
      }

      .card-columns {
        max-width: 800px;
        margin: 0 auto;
      }

      .card:hover {
        transform: translateY(-0.1rem);
      }
      .create { margin :0.8rem
      }

      .jumbotron{
      font-weight: 800;
      }


    </style>
  </head>

  <body>
    <!-- NAV -->
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Gossip Project</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="http://localhost:3000/">Accueil<span class="sr-only"></span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/team">Notre équipe</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/contact">Nous contacter</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>

    <!-- MAIN -->

    <main>
      <div class="jumbotron">
        <h1 class="display-4">Bienvenue à toi fils du Rohan !</h1>
        <p class="lead">Voici les comtes de la Terre du Milieu :</p>
        <hr class="my-4">
        <p>“Un soleil rouge se lève. Beaucoup de sang a du couler cette nuit... ”</p>
      </div>

      <a class="btn btn-light btn-lg create" href="/form"> Créer un potin </a>
    

      <!-- Potins pré-enregistrés en BDD -->

      <div class="row">
        <% @gossips.each_with_index do |gossip| %>
          <div class="col-md-4 mb-4">
            <div class="card text-white bg-dark">
              <div class="card-header"><%= gossip.title %></div>
              <div class="card-body">
                <p class="card-text"><%= truncate(gossip.content, length:20, separator: ' ') %></p>
                <a class= "btn btn-light" href="<%=user_path(gossip.user.id)%>">Auteur</a>
                <%= link_to "Voir le potin", "/show_new_gossip/#{gossip.id}", class: "btn btn-light" %>
                <div class="card-footer card-text">
            Posté le <%= gossip.created_at.strftime("%d/%m/%Y") %>
          </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>

    </main>

  </body>
</html>

app/views/gossips/show_new_gossip.html.erb
  <!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Teams</title>

    <style>
      .bg-light {
        background-color: #bd915a!important;
      }

      .card {
       
      display: flex; 
      justify: center;
      width: 10rem; 
      margin: 1rem;
      border-radius: 20px;
      }

      button{
      margin: 0.5rem;
      }

    </style>

  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Gossip Project</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="http://localhost:3000/">Accueil<span class="sr-only"></span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/team">Notre équipe</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/contact">Nous contacter</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>

    <div>
      <p>Le titre du potin : <%= @gossip.title%></p>
      <p>Le potin : <%= @gossip.content%></p>
      <p>Nom de l'auteur : <a href="<%=user_path(@user)%>"><%= @user.first_name%></a></p>
      <p>Ville de l'auteur : <a href="<%=city_path(@city)%>"><%= @user.city.name%></a></p>
    </div>

    <p> Date de création du potin : <%= @gossip.created_at %></p>

    <%= button_to "Editer le potin", edit_gossip_path, method: :get %>

    <%= button_to "Supprimer le potin", gossip_path, form: { data: { turbo_confirm: "Veux-tu supprimer ce potin ?" } }, style:"display: inline;", method: :delete %>


<!-- Formulaire de création d'un commentaire -->
<hr>
<%= form_tag(gossip_comments_path(@gossip.id), method: :post) do %>
  <%= label_tag 'Ajouter un commentaire' %>
  <br><br>
  <div>
    <%= text_area_tag 'content', nil, placeholder: "Votre commentaire...", rows: 3, cols: 50 %>
  </div>
  <br/>
  <%= submit_tag "Nouveau commentaire", class:"spec_btn", data: {turbo:false}%>
<% end %>


<!-- Publication des commentaires-->
<hr>
<h2> Commentaires déjà publiés </h2>
<br/>
<div class="text-center"> Il y a actuellement <%= @gossip.comments.count %> commentaires publiés. </div>
<br/>
<div class="row justify-content-center">
  <% @gossip.comments.reverse_each do |comment| %>
    <div class="col-lg-2 col-md-2 col-sm-2">
      <div class="card text-center">
        <div class="card-body">
          <h5 class="card-title"><%= comment.user.first_name %> <%= comment.user.last_name %></h5>
          <p class="card-text"><%= comment.content %></p>
          <%= button_to "Editer le commentaire",  edit_gossip_comment_path(@gossip, comment.id), class:"solu_description spec_btn", method: :get %>
        </div>
      </div>
    </div>
  <% end %>
</div>


  </body>
  </html>

app/views/users/show.html.erb
 <!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Teams</title>

    <style>
    .bg-light {
    background-color: #bd915a!important;
    }

    </style>
    
</head>
   
   <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Gossip Project</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="http://localhost:3000/">Accueil<span class="sr-only"></span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/team">Notre équipe</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/contact">Nous contacter</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>
 
 
 <div>
<p> Prénom : <%= @user.first_name %></p>
<p> Nom de famille : <%= @user.last_name %></p>
<p> Description : <%= @user.description %></p>
<p> E-mail : <%= @user.email %></p>
<p> Age : <%= @user.age %></p>
<p> Ville : <%= @user.city.name %></p>
</div>